apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
    - port: 80 #exposed port
      targetPort: 5000 # internal (container) port
  selector:
    name: hello-kubernetes